#! /usr/bin/env python

#global info

# header info
NVRAM_MAGIC = 0xaacc1122
NVRAM_VERSION = 0x20111122
NVRAM_H_BASE_ADDR = 0



# record infomation
NVRAM_INVALID_ID = 0xfffffffe
NVRAM_FREE_ID = 0xffffffff
NVRAM_INVALID_IND = 0xfffffffe 
NVRAM_INVALID_CRC = 0x0

NVRAM_DATA_SIZE = 496
NVRAM_BLOCK_SIZE = 512

NVRAM_R_BASE_ADDR = 0x1200

# NVRAM_NDT_BASE_ADDR = 0x200

NVRAM_ENTRIES_COUNT = 512

# DSM_NVRAM_BASE_ADDR = 0
NVRAM_H_SIZE = 512			# sizeof(NVRAM_H_INFO)
NVRAM_ND_SIZE =	8			# sizeof(NVRAM_ND_INFO)
NVRAM_R_SIZE = 	512			# sizeof(NVRAM_R_INFO)
# NVRAM_REF_SIZE = sizeof(NVRAM_REF)
# NVRAM_INFO_SIZE = sizeof(NVRAM_INFO)
NVRAM_NDT_BASE_ADDR = (((NVRAM_H_SIZE + NVRAM_R_SIZE -1)/NVRAM_R_SIZE)*NVRAM_R_SIZE)
NVRAM_NDT_SIZE = (((NVRAM_ENTRIES_COUNT*NVRAM_ND_SIZE + NVRAM_R_SIZE - 1)/NVRAM_R_SIZE)*NVRAM_R_SIZE)
NVRAM_R_BASE_ADDR = (((NVRAM_NDT_BASE_ADDR + NVRAM_NDT_SIZE +NVRAM_BLOCK_SIZE-1)/NVRAM_BLOCK_SIZE)*NVRAM_BLOCK_SIZE)

# NVRAM_R_COUNT = ((nvram_GetDevSize() - NVRAM_R_BASE_ADDR)/NVRAM_R_SIZE)



# NVRAM_IS_VALID_ID(id) = (id < NVRAM_INVALID_ID && id < NVRAM_FREE_ID)
# NVRAM_IS_VALID_RN(rn) = (rn < NVRAM_R_COUNT)
# NVRAM_IS_VALID_NDN(ndn) = (ndn < NVRAM_ENTRIES_COUNT)

NVRAM_STATUS_FREE = 0x01
NVRAM_STATUS_INVALID = 0x02

NVRAM_STATUS_USED = 0x04
NVRAM_STATUS_VALID = 0x08


# NVRAM_INVALID_RN = NVRAM_R_COUNT  
# NVRAM_INVALID_NDN = NVRAM_ENTRIES_COUNT


CALL_LOG_MAX_RECORD = 20
SIM_NUMBER = 1


NVRAM_DEFAULT_VALUE = 0xff

NVRAM_GROUP_NR = 16

NVRAM_INVALID_ND = 0xffffffff

NDN_IS_EXIST = 1
NDN_NOT_EXIST = 2

NVRAM_CHECKOUT_RESULT_OK = 1
NVRAM_CHECKOUT_RESULT_ERR = 0


def NVRAM_NR_COUNT(size):
	return ((size + NVRAM_DATA_SIZE - 1)/NVRAM_DATA_SIZE)



NVRAM_EF_ALM_SPOF_DATA_LID = 56


MAX_PB_NUMBER_CNT = 3

NVRAM_PHB_NVRAM_LID = 300
NVRAM_DIALEDCALL_NVRAM_LID = 301
NVRAM_RECVDCALL_NVRAM_LID = 302
NVRAM_MISSEDCALL_NVRAM_LID = 303
NVRAM_REJECTEDCALL_NVRAM_LID = 304
NVRAM_PHONELOCK_NVRAM_LID = 305
NVRAM_SMSPROFNE_NVRAM_LID = 306

NVRAM_EF_PHB_SOMEFIELDS_LID = 319



NVRAM_UNIT = (\
(NVRAM_PHB_NVRAM_LID,1),\
(NVRAM_DIALEDCALL_NVRAM_LID,0),\
(NVRAM_DIALEDCALL_NVRAM_LID,1),\
(NVRAM_EF_PHB_SOMEFIELDS_LID,1),\
(NVRAM_EF_ALM_SPOF_DATA_LID,1)
)
